config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get 'home' => 'welcome#home'
  get 'tournaments' => 'welcome#tournaments'
  get 'palmares' => 'welcome#palmares'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/devel/emails"
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end

  def tournaments
  end

  def palmares
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Manquers and Commanders - Casuals gamers of destruction">
  <meta name="author" content="manquersandcommanders.com">

  <title>Manquers & Commanders</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "shared/navbar" %>

  <div class="container">
    <%= render "shared/notice" %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Ver menú</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Manquers & Commanders', root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Inicio', home_path %></li>
        <li><%= link_to 'Torneos', tournaments_path %></li>
        <li><%= link_to 'Palmarés', palmares_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notice.html.erb
<% if notice.present? %>
  <div class="alert alert-info">
    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
    <h4><i class="icon fa fa-info"></i> ¡Acción realizada con éxito!</h4>
    <%= notice %>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-danger">
    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
    <h4><i class="icon fa fa-info"></i> ¡Hubo un error!</h4>
    <%= alert %>
  </div>
<% end %>

app/views/welcome/home.html.erb
<div class="wrapper home">
  <h1><b>Fran!</b> Cómeme los webos!</h1>
  <%= image_tag 'penis.png' %>
</div>

app/views/welcome/palmares.html.erb
<section class="header-home">
  <h1>Manquers & Commanders</h1>
  <span>Todos nuestros trofeos Nacionales e Internacionales</span>
</section>
  
<section class="module-win">
  <h3>1er premio en el I Torneo de COD4, en la Felanitx-weekend 2014</h3>
  <span>Pese a tener a la estrella en dudosas condiciones y sin la equipación oficial, la organización nos hizo el favor de dejarnos jugar la final, donde se barrio literalmente a los oponentes</span>
</section>

<section class="module-win">
  <h3>Diploma semifinalistas en el I Torneo de LoL, en la Felanitx-weekend 2014</h3>
  <span>Este valioso diploma se vio complementado con el Premio "FairPlayEnTop". Este premio se consiguio a base de no realizar ni un gank en top durante todo el torneo.</span>
</section>

<section class="module-win">
  <h3>1er premio en la XXVI edición del prestigioso DefconMidnightTournament</h3> 
  <span class="kh7">Esta victoria se consiguio pese a tener a KH7 en el equipo rival, considerado TOP3 EUW por aquel entonces.</span>
	<a class="btn btn-primary" role="button" data-toggle="collapse" href="#kh7" aria-expanded="false" aria-controls="kh7">
	Resumen de la final
	</a>
	<div class="collapse" id="kh7">
		<%= image_tag("kh7_image.gif") %>
	</div>
</section>

app/views/welcome/tournaments.html.erb
<section class="header-home">
  <h1>Manquers & Commanders</h1>
  <span>Asociación de 'gamers' de andar por casa. La fama no nos ciega.</span>
</section>

<div class="content-home">
  <span>Torneos patrocinados por M&C en la FelanitxWeekendParty.</span>
</div>

<section class="module-hs">
  <h3>Torneo de Hearthstone:</h3>
  <ul>
    <li>BO3 rounds</li>
    <li>Playoff mode</li>
    <li>Win and loosers brackets</li>
    <li>Premio: Una baraja española de cartas y diploma acreditado</li>
  </ul>
</section>

<section class="module-q3">
  <h3>Torneo de Quake 3:</h3>
  <ul>
    <li>1vs1 versus</li>
    <li>BO3 rounds</li>
    <li>10 min round</li>
    <li>Win and loosers brackets</li>
    <li>Premio: Una caja surtido Cuétara, lata de chipirones en su salsa y diploma acreditado</li>
  </ul>
</section>

<section class="module-lol">
  <h3>TLeague Of Legends</h3>
  <div class="manquers-orange">
    <span>Manquers Orange:</span>
    <ul>
      <li>name001</li>
      <li>name002</li>
      <li>name003</li>
      <li>name004</li>
      <li>name005</li>
    </ul>
  </div>
  <div class="manquers-blue">
    <span>Manquers Blue:</span>
    <ul>
      <li>name001</li>
      <li>name002</li>
      <li>name003</li>
      <li>name004</li>
      <li>name005</li>
    </ul>
  </div>
</section>